name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: extractions/setup-just@v4

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - run: just tidy

      - run: just ci

      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          fail_ci_if_error: true
          use_oidc: true

      - uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12.2

  walkthrough:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - uses: extractions/setup-just@v4

      - run: just walkthrough
